### ISSUE TITLE
/Login/Admin

### ISSUE THREAD

**Issue by kerberos7358** [DMU-CTEC2902/HugoWasLate-Repo#48]
Admin Should be able to block Users

**Comment by HugoHSH** [comment]
Admin Should be able to delete comment

**Comment by HugoHSH** [comment]
Admin can delete comments on movie

**Comment by HugoHSH** [comment]
Admin can delete movie, post and people.

**Comment by HugoHSH** [comment]
Admin can display the delete comments button.On the movie page is working, but the forum and people page is not working
