### ISSUE TITLE
/Comment 

### ISSUE THREAD

**Issue by HugoHSH** [DMU-CTEC2902/HugoWasLate-Repo#49]
User need to login first and comment

**Comment by kerberos7358** [comment]
Now user can login and comment

**Comment by HugoHSH** [comment]
Person page fix

**Comment by HugoHSH** [comment]
Movie page fix

**Comment by HugoHSH** [comment]
When user login cant comments in movie, forum and people page

**Comment by HugoHSH** [comment]
User can comments on the movie and the forum

**Comment by HugoHSH** [comment]
User comment on the people, it not display on it

**Comment by HugoHSH** [comment]
Delete comments is not working on forum page

**Comment by HugoHSH** [comment]
Delete comments is not working on people page

**Comment by kerberos7358** [comment]
> 
> 
> User comment on the people, it not display on it

Fixed

**Comment by kerberos7358** [comment]
> 
> 
> Delete comments is not working on people page

Fixed
