### ISSUE TITLE
/Movie /AddMovie

### ISSUE THREAD

**Issue by HugoHSH** [DMU-CTEC2902/HugoWasLate-Repo#56]
If the Movie name the blank should have error label remind user field it

**Comment by kerberos7358** [comment]
The rating can go over 10 but it shouldn't.

**Comment by kerberos7358** [comment]
The Rating can be minus but it shouldn't

**Comment by HugoHSH** [comment]
Remove the Price

**Comment by HugoHSH** [comment]
Removed the price

**Comment by HugoHSH** [comment]
> The Rating can be minus but it shouldn't

Fit it

**Comment by HugoHSH** [comment]
> The rating can go over 10 but it shouldn't.

Fit it

**Comment by kerberos7358** [comment]
Create movie shows error if there are blank fields
