### ISSUE TITLE
/Movie /Details

### ISSUE THREAD

**Issue by HugoHSH** [DMU-CTEC2902/HugoWasLate-Repo#70]
The "AddPeopleToMovie" should hide. User can add people to movie when he is not login

**Comment by HugoHSH** [comment]
User can delete comments when he is not login

**Comment by HugoHSH** [comment]
> The "AddPeopleToMovie" should hide. User can add people to movie when he is not login

Fix it

**Comment by HugoHSH** [comment]
> User can delete comments when he is not login

Fit it

**Comment by HugoHSH** [comment]
AddPeopleToMovie is disappear

**Comment by georgehwc** [comment]
Just admin can addpeopletomovie now
